language: php

php:
    - "5.6"
    - "5.5"
    - "5.4"

env:
    - PHPUNIT_VERSION='3.7.*'

before_script:
    - composer require --no-update phpunit/phpunit=$PHPUNIT_VERSION
    - composer install --prefer-source

script:
    - vendor/bin/phpunit
